name: "Test workflow"
on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  call_workflow:
    uses: Iosevka-NerdFont/workflows/.github/workflows/patch-font.yml@dev
    with:
      asset_name: "IosevkaAile"
